source 'http://rubygems.org'

gem 'rails', '3.0.1'

# Bundle edge Rails instead:
# gem 'rails', :git => 'git://github.com/rails/rails.git'

gem 'sqlite3-ruby', :require => 'sqlite3'
gem 'authlogic', :git => 'git://github.com/odorcicd/authlogic.git', :branch => 'rails3'
gem 'meta_where'
gem 'rufus-scheduler'
# gem 'cancan'
#gem 'delayed_job', :git =>"git://github.com/collectiveidea/delayed_job.git"

group :development do
  gem 'rails3-generators'
  gem 'thin'
end

group :test, :development do
  gem 'rspec-rails', "2.0.1"
end

group :test do
  gem 'cucumber-rails'
  gem 'cucumber'
  gem 'capybara'
  gem 'factory_girl_rails'
  gem 'database_cleaner'  
  gem 'pickle'
  gem 'autotest'
  gem 'autotest-rails-pure'
  gem 'autotest-fsevent'
end


# Use unicorn as the web server
# gem 'unicorn'

# Deploy with Capistrano
# gem 'capistrano'

# To use debugger
# gem 'ruby-debug'

# Bundle the extra gems:
# gem 'bj'
# gem 'nokogiri', '1.4.1'
# gem 'sqlite3-ruby', :require => 'sqlite3'
# gem 'aws-s3', :require => 'aws/s3'

# Bundle gems for the local environment. Make sure to
# put test-only gems in this group so their generators
# and rake tasks are available in development mode:
# group :development, :test do
#   gem 'webrat'
# end
